Vagrant.configure("2") do |config|
  VM_BOX = "debian/bookworm64"
  VM_MEMORY = 512
  VM_CPU = 1

  # /!\ change machine names to stud logins
  MACHINES = [
    { name: "server", hostname: "nfauconnS",   ip: "192.168.56.110" },
    { name: "serverWorker", hostname: "nfauconnSW",  ip: "192.168.56.111" }
  ]

  MACHINES.each do |machine|
    config.vm.define machine[:name] do |vm_config|
      vm_config.vm.box = VM_BOX
      vm_config.vm.hostname = machine[:hostname]
      vm_config.vm.network "private_network", ip: machine[:ip]
      vm_config.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus  = VM_CPU
      end
      # vm_config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   ufw disable
      #   apt-get install -y apache2
      # SHELL

    end
  end
end

