Vagrant.configure("2") do |config|
  VM_BOX = "debian/bookworm64"
  VM_MEMORY = 1024
  VM_CPU = 1

  # /!\ change machine names to stud logins
  MACHINES = [
    { name: "nfauconnS",  hostname: "nfauconnS",   ip: "192.168.56.110" },
    { name: "nfauconnSW", hostname: "nfauconnSW",  ip: "192.168.56.111" }
  ]

  MACHINES.each do |machine|
    config.vm.define machine[:name] do |vm_config|
      vm_config.vm.box = VM_BOX
      vm_config.vm.hostname = machine[:hostname]
      vm_config.vm.network "private_network", ip: machine[:ip]
      vm_config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", machine[:name]]
        vb.memory = VM_MEMORY
        vb.cpus  = VM_CPU
      end

      vm_config.vm.provision "shell", inline: <<-SHELL
        set -eux
        sudo apt-get update
        sudo apt-get install -y curl
      SHELL

      if machine[:name] == "nfauconnS"
        vm_config.vm.provision "shell", inline: <<-SHELL
        set -eux
        curl -sfL https://get.k3s.io | sh -
        sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
        SHELL
      else
        vm_config.vm.provision "shell", inline: <<-SHELL
        set -eux
        TOKEN=$(cat /vagrant/node-token)
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN sh -
        SHELL
      end

    end
  end
end

