Vagrant.configure("2") do |config|
  VM_BOX = "debian/bookworm64"
  VM_MEMORY = 512
  VM_CPU = 1

  # /!\ change machine names to stud logins
  MACHINES = [
    { name: "server", hostname: "nfauconnS",   ip: "192.168.56.110" },
    { name: "serverWorker", hostname: "nfauconnSW",  ip: "192.168.56.111" }
  ]

  MACHINES.each do |machine|
    config.vm.define machine[:name] do |vm_config|
      vm_config.vm.box = VM_BOX
      vm_config.vm.hostname = machine[:hostname]
      vm_config.vm.network "private_network", ip: machine[:ip]
      vm_config.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus  = VM_CPU
      end
      vm_config.vm.provision "shell", inline: <<-SHELL
        set -e

        echo "Hostname: $(hostname)" > /tmp/vagrant-check.txt
        echo "IP: $(hostname -I)" >> /tmp/vagrant-check.txt
        echo "CPU: $(nproc)" >> /tmp/vagrant-check.txt
        echo "RAM: $(free -m | grep Mem | awk '{print $2}')" >> /tmp/vagrant-check.txt

        sudo apt update
        sudo apt install -y curl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client
      SHELL
    end
  end
end

